### ISSUE TITLE
Mozilla Persona einbinden

### ISSUE THREAD

**Issue by commel** [Holarse-Linuxgaming/website#50]
Login über Mozilla Persona ermöglichen https://login.persona.org/

**Comment by NoXPhasma** [comment]
Brauchen wir das wirklich? Ich traue solchen Diensten ja nicht, ein Passwort für ganz viele Dienste bis dann eines tages der Supergau ausbricht.

**Comment by commel** [comment]
Brauchen tun wir das nicht.

**Comment by Lucki** [comment]
Wird leider eingestellt.

**Comment by Lucki** [comment]
Inoffizielle fortführung als [Portier](https://portier.github.io/).

> Portier is inspired by many projects and considers itself a spiritual successor to Mozilla Persona.

**Comment by commel** [comment]
Wir wollen eigentlich keine externen Logins.
