### ISSUE TITLE
Benutzer in Beiträgen verlinken

### ISSUE THREAD

**Issue by commel** [Holarse-Linuxgaming/website#51]
Benutzer sollen einfach in Beiträgen erwähnt und verlinkt werden können, indem man das aus Twitter bekannte Verfahren benutzt. Also @benutzername wird dann in einen Link auf den Benutzer umgewandelt. Zudem kann dann der Benutzer, je nach seinen Einstellungen, auch informiert werden.

**Comment by BOHverkill** [comment]
Also genau so wie bei GitHub

@Mentions

**Comment by commel** [comment]
Ja genau das
