### ISSUE TITLE
pkgs.org einbinden

### ISSUE THREAD

**Issue by Lucki** [Holarse-Linuxgaming/website#57]
Zeigt automatisiert an, ob Pakete für die eigene Distribution (im Profil einstellbar) verfügbar sind.
Wenn der Profileintrag nicht vorhanden ist werden alle verfügbaren Distributionen angezeigt.

http://pkgs.org/

**Comment by commel** [comment]
Das ist super, aber wie binden wir das ein? Hab auf die schnelle keine API gefunden.

**Comment by Lucki** [comment]
Mal den Entwickler kontaktieren, vielleicht baut der sowas ein.
Ansonsten muss @SuperNascher mit seinen Skillz da ran.

**Comment by NoXPhasma** [comment]
Das ist ne coole Idee, gibt es ne Möglichkeit daraus ne Datenbank zu erstellen, anstelle von jedes mal bei der API nachfragen wenn jemand ein Spiel ansieht?

**Comment by commel** [comment]
Wenn wir an die API rankommen können wir daraus die lokale Datenbank erzeugen.

**Comment by SuperNascher** [comment]
Wenn sich der Entwickler der Webseite nicht meldet, könnten wir mit PHP oder Python eine kleine API basteln, die sich die Informationen aus den div- und ul-Elementen abgreift.
