### ISSUE TITLE
Pro Nutzer Version von Spiele Artikel

### ISSUE THREAD

**Issue by Jorval** [Holarse-Linuxgaming/website#70]
Moinsen,
Das wird jetzt wahrscheinlich kontrovers ;)
Ich habe das Problem auch schon bei einigen anderen Wikis, aber gerade bei Spielen und Meinungen zu Spielen wäre es da nicht schön wenn man nicht nur einen Artikel hätte der von vielen Usern bearbeitet wurde sondern zwischen den einzelnen Benutzern umschalten könnte?

Mir ist klar das das eigentlich dem Sinn eines Wikis und dem gemeinschaftlichen arbeiten entgegenstrebt, und bisher hat es meines Wissens nach in der Holarse community auch noch keinen ArtikelKrieg wegen unterschiedlicher Auffassung einzelner User gegeben.

Ich wollte diesen Vorschlag trotzdem machen da ich glaube das dies durchaus interessant wäre mehrere Meinungen zu einem Spiel abrufen zu können

[Mockup](https://cloud.jorval.de/index.php/s/0sM5jD3GjXkah5L)

**Comment by commel** [comment]
Prinzipiell eine gute Idee. Praktisch kriegen wir kaum jemanden dazu überhaupt einen Artikel / Review zu schreiben. Wie wäre es, wenn man die Idee als Seitenkommentare an jeweilige Zeilen heftet? Ähnlich wie in bekannten Textverarbeitungsprogrammen.

**Comment by Jorval** [comment]
Ups ;) hab den Kommentar hier verpasst!
Naja ich habe mir gedacht wenn ich schon Artikel schreibe (was äussertst selten vorkommt!!!) dann doch eher ausführlich.
Alternativ würde ich mir ein neues GhostBlog einrichten dort meinen Artikel schreiben und dann in dem Holarse Artikel darauf verlinken.
Medien wie Screenshots oder hoffentlich bald mal wieder Videos kann ich ja zus. dem Wikibeitrag hinzufügen wenn das gewünscht ist.

**Comment by commel** [comment]
Ich hab über diese Idee nochmal nachgedacht und bin zu der Überzeugung gekommen, dass man es mit einem anderen Anwendungsfall gut zusammenlegen könnte.

Prinzipiell wird ein Artikel von Zeit zu Zeit generalüberholt, sprich, wenn ein Spiel aus einer Beta rauskommt, oder schon einige Zeit vergangen ist, oder wenn ein Artikel sich mit der Wine-Version befasst, aber inzwischen ein nativer Port veröffentlicht worden ist.

Revisionen helfen da nur bedingt, da man eigentlich einige Revisionen behalten möchte. Die erste Idee war es Revisionen zu taggen, ähnlich wie man es in Git macht. Das bringt leider das Problem mit sich, dass man dann Tippfehler oder Anpassungen kurz danach nicht mehr mitbekommt. 

Da kommt nun deine Anregung ins Spiel. Man könnte verschiedene Versionen des Artikels anbieten. Anstatt diese Benutzerabhängig zu machen, kann man anstelle einer neuen Revision eine neue Version machen, die dann wiederum selbst Revisionen hat. Also eigentlich eine Art git-branch.

Das Feature würde ich so gerne umsetzen, allerdings in einer späteren Version.

**Comment by Jorval** [comment]
Moin Bernd,

Schön das der Vorschlag zu weiteren Ideen führt ;)

Ich wollte damit auch keinesfalls den wikicharakter und das gemeinschaftliche Arbeiten in frage stellen.
Spieler sind halt unterschiedlich und so auch ihre Meinungen zu einzelnen Aspekten von Spielen wie Grafik oder Spielmechanik. Zwar findet man eigentlich nie negative Artikel aber die Spieleartikel auf Holarse haben halt alle immer den individuellen Charakter des Verfassers.
Ich dachte das man damit vllt. einen Strukturell wertneutralen Artikel auf der "Hauptseite" verfasst und jeder Nutzer sein Review/Meinung dann in einem eigenen Tab hinterlassen kann.

Die Idee das für Unterschiedliche "Branches" zu nutzen finde ich auch ziemlich gut, Gutes Beispiel wäre Stellaris! Mit CHerry hat sich das Spiel in seinen Grundfesten erneuert und ist nun eigentlich ein ganz neues Spiel. (Gut das kommt ausser bei Paradox wohl eher selten vor!)
Aber gerade hier sieht man wie unterschiedlich die Meinungen dazu auseinanderdriften, das Feedback auf Steam ist sehr gemischt.

Das mit den Reviews wollte ich nur nochmal loswerden ;) vllt. fliesst das ja auch mit in deine Überlegungen ein ;)
